// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todolistapi.Models;

namespace todolistapi.Migrations
{
    [DbContext(typeof(ToDoListContext))]
    partial class ToDoListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("todolistapi.Models.Todolist", b =>
                {
                    b.Property<int>("itemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("itemCategory")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("itemDescription")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("itemDueDate")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("itemEstimate")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("itemImportance")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("itemName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("itemStatus")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("itemID");

                    b.ToTable("ToDoLists");
                });
#pragma warning restore 612, 618
        }
    }
}
